### ISSUE TITLE
drop in a deploybot config

### ISSUE THREAD

**Issue by tedivm** [katrinajaneczko/gha-example#2]
Create the file `.github/dependabot.yml` and populate it with this:

```
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

That will update all your actions for you so you stop getting the node deprecation error.
